name: Read Power Platform Settings
author: Andersg
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
  parentTelemetryScopeJson:
    description: Specifies the parent telemetry scope for the telemetry signal
    required: false
    default: '7b7d'
  deploySettings: 
    description: The deploy settings
    required: false
    default: '{}'
  authSettings: 
    description: The auth settings
    required: false
    default: '{}'

runs:
  using: composite
  steps:
    - name: run
      shell: ${{ inputs.shell }}
      env:
        _deploySettings: ${{ inputs.deploySettings }}
        _authSettings: ${{ inputs.authSettings }}
      run: ${{ github.action_path }}/ParseDeploymentAndAuthSettings.ps1 -deplaySettings ${{env._deploySettings}} -authSettings ${{env._authSettings}}

branding:
  icon: terminal
  color: blue
