name: DeployPowerPlatformSolution
author: Andersg
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
  actor:
    description: The GitHub actor running the action
    required: false
    default: ${{ github.actor }}
  token:
    description: The GitHub token running the action
    required: false
    default: ${{ github.token }}
  parentTelemetryScopeJson:
    description: Specifies the parent telemetry scope for the telemetry signal
    required: false
    default: '7b7d'
  artifact:
    description: The Power Platform solution
    required: false
    default: '.'
  version:
    description: The Power Platform solution version
    required: false
    default: '.'
  companyId:
    description: The Power Platform solution version
    required: false
    default: '.'
  environmentName:
    description: The Power Platform solution version
    required: false
    default: '.'
    
runs:
  using: composite
  env: 
    tempSolutionPath: .artifacts/tempPPSolution
  steps:
    - name: Unpack solution artifact
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: ${{inputs.artifact}}
        solution-folder: ${{env.tempSolutionPath}}
        solution-type: "Unmanaged"
        overwrite-files: true
        process-canvas-apps: true

    - name: Rebuild solution
      uses: BusinessCentralDemos/AL-Go-Actions/BuildPowerPlatform@PowerPlatform
      with:
        shell: ${{ inputs.shell }}
        parentTelemetryScopeJson: ${{ inputs.parentTelemetryScopeJson }}
        solution: ${{ env.tempSolutionPath }}
        version: ${{ inputs.version }}
        companyId: ${{ inputs.companyId }}
        environmentName: ${{ inputs.environmentName }}
branding:
  icon: terminal
  color: blue
