name: DeployPowerPlatformSolution
author: Andersg
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
  actor:
    description: The GitHub actor running the action
    required: false
    default: ${{ github.actor }}
  token:
    description: The GitHub token running the action
    required: false
    default: ${{ github.token }}
  parentTelemetryScopeJson:
    description: Specifies the parent telemetry scope for the telemetry signal
    required: false
    default: '7b7d'
  artifact:
    description: The Power Platform solution
    required: false
    default: '.'
  version:
    description: The Power Platform solution version
    required: false
    default: '.'
  deploySettings: 
    description: The deploy settings
    required: false
    default: '{}'
  authSettings: 
    description: The deploy settings
    required: false
    default: '{}'
    
env: 
  tempSolutionPath: .artifacts/tempPPSolution
runs:
  using: composite
  steps:
    - name: test input
      shell: ${{inputs.shell}}
      run: |
        Write-Host "Deploy settings: ${{ inputs.deploySettings }}";
        Write-Host "Auth settings: ${{ inputs.authSettings }}";
        Write-Host "Artifact: ${{ inputs.artifact }}";  
        ls ;
        ls ${{ inputs.artifact }};
        Get-ChildItem -Recurse -Path "${{ inputs.artifact }}"
  
    - name: Unpack solution artifact
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: ${{inputs.artifact}}
        solution-folder: ${{env.tempSolutionPath}}
        solution-type: "Unmanaged"
        overwrite-files: true
        process-canvas-apps: true

    - name: Rebuild solution
      uses: BusinessCentralDemos/AL-Go-Actions/BuildPowerPlatform@PowerPlatform
      with:
        shell: ${{ inputs.shell }}
        parentTelemetryScopeJson: ${{ inputs.parentTelemetryScopeJson }}
        solution: ${{ env.tempSolutionPath }}
        version: ${{ inputs.version }}
        companyId: ${{ inputs.companyId }}
        environmentName: ${{ inputs.environmentName }}
branding:
  icon: terminal
  color: blue
