name: DeployPowerPlatformSolution
author: Andersg
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
  actor:
    description: The GitHub actor running the action
    required: false
    default: ${{ github.actor }}
  token:
    description: The GitHub token running the action
    required: false
    default: ${{ github.token }}
  parentTelemetryScopeJson:
    description: Specifies the parent telemetry scope for the telemetry signal
    required: false
    default: '7b7d'
  artifact:
    description: The Power Platform solution
    required: false
    default: '.'
  version:
    description: The Power Platform solution version
    required: false
    default: '.'
  deploySettings: 
    description: The deploy settings
    required: false
    default: '{}'
  authSettings: 
    description: The deploy settings
    required: false
    default: '{}'
    
runs:
  using: composite
  steps:
    - name: test input
      shell: ${{inputs.shell}}
      run: |
        Write-Host "Deploy settings: ${{ inputs.deploySettings }}";
        Write-Host "Auth settings: ${{ inputs.authSettings }}";
        Write-Host "Artifact: ${{ inputs.artifact }}";  
        Get-ChildItem -Recurse -Path "${{ inputs.artifact }}"
        
        
    - name: findSolutionFile
      shell: ${{inputs.shell}}
      run: |
            $filePath = Get-ChildItem -Path $path -Recurse -File | Select-Object -ExpandProperty FullName;
            Write-Host "Find Power Platform solution file";
            foreach($file in $filePath){
                if($file.contains("-PowerPlatformSolution-")){
                    Write-Host "Found match:"$file;
                    echo "powerPlatformSolutionPath=$file" >> $env:GITHUB_ENV
                    return;
                }
            }
  
    - name: Unpack solution artifact
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: ${{ env.powerPlatformSolutionPath }}
        solution-folder: .artifacts/tempPPSolution/source
        solution-type: "Unmanaged"
        overwrite-files: true
        process-canvas-apps: true
    
    - name: see files
      shell: ${{inputs.shell}}
      run: ls .artifacts/tempPPSolution/source
    
    - name: Parse deployTo JSON
      shell: ${{inputs.shell}}
      run: |
        $json = '${{ inputs.deploySettings }}'
        $obj = ConvertFrom-Json $json

        $environmentName = $obj.environmentName;
        Write-Output $environmentName
        echo "environmentName=$environmentName" >> $env:GITHUB_ENV

        $environmentUrl = $obj.'environment-url';
        Write-Output $environmentUrl
        echo "environmentUrl=$environmentUrl" >> $env:GITHUB_ENV
        
        $bcEnvironment = $obj.bcEnvironment;
        Write-Output $bcEnvironment
        echo "bcEnvironment=$bcEnvironment" >> $env:GITHUB_ENV

        $bcCompanyId = $obj.bcCompanyId;
        write-output $bcCompanyId
        echo "bcCompanyId=$bcCompanyId" >> $env:GITHUB_ENV

    - name: Rebuild solution
      uses: BusinessCentralDemos/AL-Go-Actions/BuildPowerPlatform@PowerPlatform
      with:
        shell: ${{ inputs.shell }}
        parentTelemetryScopeJson: ${{ inputs.parentTelemetryScopeJson }}
        solutionPath: .artifacts/tempPPSolution/source
        solutionName: ppsolution
        outputFolder: .artifacts/tempPPSolution
        version: 1.0.0.2
        companyId: ${{ env.bcCompanyId }}
        environmentName: ${{ env.bcEnvironment }}
        
    - name: Parse auth context
      shell: ${{inputs.shell}}
      run: |
        $json = '${{ inputs.authSettings }}'
        $obj = ConvertFrom-Json $json

        $userName = $obj.userName;
        Write-Output "userName=$userName"
        echo "userName=$userName" >> $env:GITHUB_ENV

        $password = $obj.password;
        Write-Output "password=$password"
        echo "password=$password" >> $env:GITHUB_ENV

    - name: Who am I
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        user-name: ${{env.userName}}
        password-secret: ${{env.passeword}}
        environment-url: ${{env.environmentUrl}}

    - name: Publish solution to Power Platform
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        user-name: ${{env.userName}}
        password-secret: ${{env.passeword}}
        environment-url: ${{env.environmentUrl}}
        solution-file: .artifacts/tempPPSolution/ppsolution.zip
        force-overwrite: true
        publish-changes: true

branding:
  icon: terminal
  color: blue
