name: BuildPowerPlatformSolution
author: Andersg
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
  actor:
    description: The GitHub actor running the action
    required: false
    default: ${{ github.actor }}
  token:
    description: The GitHub token running the action
    required: false
    default: ${{ github.token }}
  parentTelemetryScopeJson:
    description: Specifies the parent telemetry scope for the telemetry signal
    required: false
    default: '7b7d'
  project:
    description: Project folder
    required: false
    default: '.'
  settingsJson:
    description: Settings from repository in compressed Json format
    required: false
    default: '{}'
  secretsJson:
    description: Secrets from repository in compressed Json format
    required: false
    default: '{}'
runs:
  using: composite
  steps:
    - name: Set up variables
      shell: pwsh
        run: |
          echo "Parsing JSON string"
          export PROPERTY1=$(echo "$inputs.settingsJson " | jq -r '.environment-url')
          export PROPERTY2=$(echo "$inputs.settingsJson " | jq -r '.bcCompanyId')
          echo "PROPERTY1=$PROPERTY1"
          echo "PROPERTY2=$PROPERTY2"

    - name: run
      shell: ${{ inputs.shell }}
      env:
        _actor: ${{ inputs.actor }}
        _token: ${{ inputs.token }}
        _parentTelemetryScopeJson: ${{ inputs.parentTelemetryScopeJson }}
        _project: ${{ inputs.project }}
        _projectDependenciesJson: ${{ inputs.projectDependenciesJson }}
        _settingsJson: ${{ inputs.settingsJson }}
        _secretsJson: ${{ inputs.secretsJson }}
      run: try { ${{ github.action_path }}/BuildPowerPlatform.ps1 -actor $ENV:_actor -token $ENV:_token -parentTelemetryScopeJson $ENV:_parentTelemetryScopeJson -project $ENV:_project -projectDependenciesJson $ENV:_projectDependenciesJson -settingsJson $ENV:_settingsJson -secretsJson $ENV:_secretsJson } catch { Write-Host "::Error::Unexpected error when running action ($($_.Exception.Message.Replace("`r",'').Replace("`n",' ')))"; exit 1 }

    - name: Update solution settings
      shell: pwsh
      run: |
        .github/actions/script/updateSolutionFile.ps1 -version ${{env.version}}

    - name: Update BC connection
      shell: pwsh
      run: |
        .github/actions/script/updateEnvironmentAndCompany.ps1 -companyId ${{secrets.bcCompanyId}} -environmentName ${{secrets.bcEnvironmentName}}

    - name: Test Pack (Not real - just workaround bug)
      uses: microsoft/powerplatform-actions/pack-solution@v0
      with:
        solution-file: forgetMe.zip
        solution-folder: ${{env.solutionName}}
        solution-type: ${{env.solutionType}}
        process-canvas-apps: true

    - name: Pack Solution
      uses: microsoft/powerplatform-actions/pack-solution@v0
      with:
        solution-file: "output/${{env.solutionName}}.zip"
        solution-folder: "${{env.solutionName}}"
        solution-type: "Unmanaged"
        process-canvas-apps: true
      
branding:
  icon: terminal
  color: blue
