name: BuildPowerPlatformSolution
author: Andersg
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
  actor:
    description: The GitHub actor running the action
    required: false
    default: ${{ github.actor }}
  token:
    description: The GitHub token running the action
    required: false
    default: ${{ github.token }}
  parentTelemetryScopeJson:
    description: Specifies the parent telemetry scope for the telemetry signal
    required: false
    default: '7b7d'
  solution:
    description: The Power Platform solution
    required: false
    default: '.'
  outputFolder:
    description: The Power Platform solution
    required: false
    default: '.'
  version:
    description: The Power Platform solution version
    required: false
    default: '.'
  companyId:
    description: The Power Platform solution version
    required: false
    default: ''
  environmentName:
    description: The Power Platform solution version
    required: false
    default: ''
    
runs:
  using: composite
  steps:
    - name: Update solution settings
      if: inputs.version
      shell: ${{inputs.shell}}
      run: |
        ${{ github.action_path }}\updateSolutionFile.ps1 -version ${{inputs.version}}

    - name: Update BC connection
      if: inputs.companyId
      shell: ${{inputs.shell}}
      run: |
        ${{ github.action_path }}\updateEnvironmentAndCompany.ps1 -companyId ${{inputs.companyId}} -environmentName ${{inputs.environmentName}}

    - name: Test Pack (Not real - just workaround bug)
      uses: microsoft/powerplatform-actions/pack-solution@v0
      with:
        solution-file: forgetMe.zip
        solution-folder: ${{inputs.solution}}
        process-canvas-apps: true

    - name: Pack Solution
      uses: microsoft/powerplatform-actions/pack-solution@v0
      with:
        solution-file: ${{inputs.outputFolder}}/${{inputs.solution}}.zip
        solution-folder: ${{inputs.solution}}
        solution-type: "Unmanaged"
        process-canvas-apps: true
        
    - name: Test Output path
      shell: ${{inputs.shell}}
      run: ls ${{inputs.outputFolder}}        
     
branding:
  icon: terminal
  color: blue
